CREATE TABLE organisations (
  id SERIAL PRIMARY KEY,
  human_id INTEGER NOT NULL REFERENCES humans(id) ON DELETE CASCADE,
  name VARCHAR(256) UNIQUE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
